config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :vote_details
  resources :ip_lists
  resources :categories
  resources :categories
  resources :questions
  resources :comments
  devise_for :users
  root 'home#index'

  post 'updateVote' => 'vote_details#create', as: :makevote
  get 'users' => 'home#index'

  namespace :api do
    get 'questions' => 'questions#index'
    get 'questions/:id' => 'questions#show'
    post 'questions' => 'questions#create', as: :api_question_create
    post 'makeComment' => 'comments#create'
    post 'sign_in'  => 'sessions#create', as: :api_sign_in
    delete 'sign_out' => 'sessions#destroy', as: :api_sign_out
    post 'register' => 'users#create', as: :api_user_create
    post 'updateVote' => 'vote_details#create', as: :makevote
  end

end

app/models/question.rb
class Question
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :user
  belongs_to :category#, index: true
  has_many :vote_details, dependent: :destroy
  has_many :comments, dependent: :destroy
  paginates_per 10

  acts_as_token_authenticatable
  field :authentication_token

  field :text,            type: String
  field :vote_count,      type: Integer
  field :vote_count_last_seen,    type: Integer, default: 0
  #field :category,        type: String



end

app/controllers/api/questions_controller.rb
class Api::QuestionsController < Api::ApiController


  acts_as_token_authentication_handler_for User
    
  def index
    render json: { questions: Question.all }
  end

  def show
    question = Question.where(id: params[:id]).first
    if question
      render status: 200, json: { questions: question }
    else
      render status: 404, json: { error: "question not found for that id" }
    end
  end

  def create

    binding.pry
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    if @question.save
      render status: 200, json: { message: "Congradulation, you made a question" }
    else
      render status: 404, json: { error: "Could not create the question" }
    end
  end

  private
  
  def question_params
    params.require(:question).permit(:text, :category)
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_filter :admin?, only: [:index, :edit, :update, :destroy]
  include QuestionsHelper

  

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    #@question = Question_id: 
    @ip = request.remote_ip
    @question = Question.find_by(id: params[:id])
    @comment = Comment.new
    @comments = Comment.all.where(question_id: params[:id])


    if current_user == User.find_by(id: @question.user_id)
      @question.vote_count_last_seen = @question.vote_details.count
      @question.save
    end

  end

  # GET /questions/new
  def new
    @question = Question.new
    @category = Category.all
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id


    #Very inefficient
    @question.category_id = Category.find_by(category: question_params[:category]).id
    #@question.category_name = question_params[:category]
    #binding.pry
    #@question.category_id = question_params[:category]

    respond_to do |format|
      if @question.save

        if Rails.env.production?
          client = twitter
          client.bearer_token
          client.update("#{@question.text} go vote now at #{request.host}/questions/#{@question.id}")
        end
        #binding.pry

        #if Rails.env.production?
        #end
        format.html { redirect_to root_url, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:text, :category)
    end

end

app/helpers/questions_helper.rb
module QuestionsHelper

    
  def twitter
  
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV["twitter_consumer_key"]
      config.consumer_secret     = ENV["twitter_consumer_secret"]
      config.access_token        = ENV["twitter_access_token"]
      config.access_token_secret = ENV["twitter_access_token_secret"]
    end

    #client.bearer_token

    client
  end

end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    
    <%= f.label :text %>
    <%= f.text_field :text, class: 'form-control' %>

    <%#= f.label :category %>
    <%#= f.text_field :category, class: 'form-control' %>

    <% @category.each do |a| %>

    <% end %>

    <%#= f.select :category, [@category.first.category] %>

    <%= f.select(:category, @category.all.map {|p| [p.category]}, :prompt => "Select a Category") %>



    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>


<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<% f = @question %>

<% if browser.mobile? %>
  <div class="row" style="margin:0; padding: 20px 5px 5px 5px; position:relative;">  
<% else %>
  <div class="row" style="margin:0; padding: 5px 30px 30px 30px position: relative;">  
<% end %>
  <div class="large-12 columns">
  
    <div class = "row">
      <div class = "large-12 columns" style="background-color: #2D95EB; height: 40px; border-radius: 6px; -moz-border-radius: 6px;">
        <div class = "question_blue_bar">Posted at: <%= f.created_at.strftime("%b %d, %Y") %></div>
      </div>
    </div>

    <div class = "row">
      <div class = "large-12 columns" style="background-color: white; height: 10px;">
      </div>
    </div>
    
    <div class = "row" style="background-color: #e4e4e4;">
    <div class = "large-12 columns">


  Posted by user: <%= f.user.email %>
  Question: <%= f.text %>
  Category: <%= f.category.category %>

  Yes: <%= f.vote_details.where(yes: true).count %>
  No: <%= f.vote_details.where(yes: false).count %>

  <% if f.vote_details.where(ip: @ip).exists? %>

        You have already voted!

  <% else %>
    <%= link_to "Yes", makevote_path(question_id: f.id, yes: true, ip: @ip), method: "post" %>
    <%= link_to "No", makevote_path(question_id: f.id, yes: false, ip: @ip), method: "post" %>
  <% end %>
  </div>
  </div>
  </div>
  </div>

<!--

  <%= form_for(@comment) do |a| %>
  <div class="actions" style = "position: absolute;">

    <% if user_signed_in? %>
      <%= a.label :Comment %>
      <%= a.text_area :text, class: 'form-control' %>
      </pre>

      <%= a.hidden_field :question_id, :value => f.id %>
      <%= a.hidden_field :user_id, :value => current_user.id %>
      <%= a.submit %>

    <% else %>
    <pre>
    Log in if you want to make a comment!!!
    </pre>
    <% end %>
  <% end %>
  </pre>

  <% @comments.each do |b| %>

  <pre>
    Username: <%= User.find_by(id: b.user_id).email %>
    Comment: <%= b.text %>
  </pre>

  <% end %>

-->







<%#= link_to 'Edit', edit_question_path(@question) %>
<%#= link_to 'Back', questions_path %>