config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :vote_details
  resources :ip_lists
  resources :categories
  resources :categories
  resources :questions
  resources :comments
  devise_for :users
  root 'home#index'

  post 'updateVote' => 'vote_details#create', as: :makevote
  get 'users' => 'home#index'

  namespace :api do
    get 'questions' => 'questions#index'
    get 'questions/:id' => 'questions#show'
    post 'questions' => 'questions#create', as: :api_question_create
    post 'makeComment' => 'comments#create'
    post 'sign_in'  => 'sessions#create', as: :api_sign_in
    delete 'sign_out' => 'sessions#destroy', as: :api_sign_out
    post 'register' => 'users#create', as: :api_user_create
    post 'updateVote' => 'vote_details#create', as: :makevote
  end

end

app/models/vote_detail.rb
class VoteDetail
  include Mongoid::Document
  include Mongoid::Timestamps
  belongs_to :question
  #validates :ip, uniqueness: {scope: [:question]}

  field :yes,         type: Boolean
  field :ip,          type: String
  field :seen,        type: Boolean, default: false

end

app/controllers/api/vote_details_controller.rb
class Api::VoteDetailsController < Api::ApiController
    
  def create

    #if ip address already exists, send back an error message
    
    @ip = request.remote_ip

    #if Question.find_by(id: vote_detail_params[:question_id]).vote_details.where(ip: @ip).exists?
    #  render json: {error: 'areadly voted'}
    #else

    @vote_detail = VoteDetail.new(vote_detail_params.merge(ip: @ip))

    
      if @vote_detail.save
       render status: 200, 
              json: 
                { test: "test",
                  vote_detail: @vote_detail,
                  questions: Question.all }
      else
        render json: @vote_detail.errors, status: :unprocessable_entity
      end
    
  end

  private
    def vote_detail_params
      params.permit(:question_id, :yes)
    end
end

app/controllers/vote_details_controller.rb
class VoteDetailsController < ApplicationController
  before_action :set_vote_detail, only: [:show, :edit, :update, :destroy]
  before_filter :admin?, only: [:show, :edit, :index, :update, :destroy]


  # GET /vote_details
  # GET /vote_details.json
  def index
    @vote_details = VoteDetail.all
  end


  # GET /vote_details/1
  # GET /vote_details/1.json
  def show
  end

  # GET /vote_details/new
  def new
    @vote_detail = VoteDetail.new
  end

  # GET /vote_details/1/edit
  def edit
  end

  # POST /vote_details
  # POST /vote_details.json
  def create

    #if ip address already exists, send back an error message
    
    @ip = request.remote_ip

    #if Question.find_by(id: vote_detail_params[:question_id]).vote_details.where(ip: @ip).exists?
    #  render json: {error: 'areadly voted'}
    #else

    @vote_detail = VoteDetail.new(vote_detail_params.merge(ip: @ip))

    respond_to do |format|
      if @vote_detail.save
        format.html { redirect_to :back, notice: 'You have successfully voted' }
        format.json { render :show, status: :created, location: @vote_detail }
      else
        format.html { render :new }
        format.json { render json: @vote_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vote_details/1
  # PATCH/PUT /vote_details/1.json
  def update
    respond_to do |format|
      if @vote_detail.update(vote_detail_params)
        format.html { redirect_to @vote_detail, notice: 'Vote detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote_detail }
      else
        format.html { render :edit }
        format.json { render json: @vote_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vote_details/1
  # DELETE /vote_details/1.json
  def destroy
    @vote_detail.destroy
    respond_to do |format|
      format.html { redirect_to vote_details_url, notice: 'Vote detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote_detail
      @vote_detail = VoteDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_detail_params
      params.permit(:question_id, :yes)
    end
end

app/helpers/vote_details_helper.rb
module VoteDetailsHelper
end

app/views/vote_details/_form.html.erb
<%= form_for(@vote_detail) do |f| %>
  <% if @vote_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote_detail.errors.count, "error") %> prohibited this vote_detail from being saved:</h2>

      <ul>
      <% @vote_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vote_details/edit.html.erb
<h1>Editing Vote Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote_detail %> |
<%= link_to 'Back', vote_details_path %>

app/views/vote_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vote Details</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vote_details.each do |vote_detail| %>
      <tr>
        <td><%= link_to 'Show', vote_detail %></td>
        <td><%= link_to 'Edit', edit_vote_detail_path(vote_detail) %></td>
        <td><%= link_to 'Destroy', vote_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote detail', new_vote_detail_path %>

app/views/vote_details/new.html.erb
<h1>New Vote Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', vote_details_path %>

app/views/vote_details/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_vote_detail_path(@vote_detail) %> |
<%= link_to 'Back', vote_details_path %>