config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :vote_details
  resources :ip_lists
  resources :categories
  resources :categories
  resources :questions
  resources :comments
  devise_for :users
  root 'home#index'

  post 'updateVote' => 'vote_details#create', as: :makevote
  get 'users' => 'home#index'

  namespace :api do
    get 'questions' => 'questions#index'
    get 'questions/:id' => 'questions#show'
    post 'questions' => 'questions#create', as: :api_question_create
    post 'makeComment' => 'comments#create'
    post 'sign_in'  => 'sessions#create', as: :api_sign_in
    delete 'sign_out' => 'sessions#destroy', as: :api_sign_out
    post 'register' => 'users#create', as: :api_user_create
    post 'updateVote' => 'vote_details#create', as: :makevote
  end

end

app/models/category.rb
class Category
  include Mongoid::Document

  has_many :questions, dependent: :destroy

  field :category,        type: String
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_filter :admin?, only: [:index, :new, :create, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @questions = Question.all.where(category_id: params[:id])
    @questions = Kaminari.paginate_array(@questions).page(params[:page]).per(10)
    @ip = request.remote_ip
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:category)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">

    <%= f.label :category %>
    <%= f.text_field :category, class: 'form-control' %>
    
    <%= f.submit %>
  
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<!-- ################### Each Question Div ################ -->

<% @questions.each do |f|%>

<% if browser.mobile? %>
  <div class="row" style="margin:0; padding: 20px 5px 5px 5px;">  
<% else %>
  <div class="row" style="margin:0; padding: 5px 30px 30px 30px;">  
<% end %>
  <div class="large-12 columns">

    <!-- ################### Top blue part ################ -->

    <div class = "row">
      <div class = "large-12 columns" style="background-color: #2D95EB; height: 40px; border-radius: 6px; -moz-border-radius: 6px;">
        <div class = "question_blue_bar">Posted at: <%= f.created_at.strftime("%b %d, %Y") %></div>        
      </div>
    </div>

    <!-- ################### White space ################ -->

    <div class = "row">
      <div class = "large-12 columns" style="background-color: white; height: 10px;">
      </div>
    </div>

   <!-- ################### Main section ################ -->

    <div class = "row" style="background-color: #e4e4e4;">
      <div class = "large-12 columns">
        <h3>Posted by user: <%= f.user.email %></h3>
        <h3>Question: <%= f.text %></h3>
        <div class = "yess">Yes: <div><%= f.vote_details.where(yes: true).count %></div></div>
        <div class = "noo">No: <div><%= f.vote_details.where(yes: false).count %></div></div> 

        <% if f.vote_details.where(ip: @ip).exists? %>
          <div>You have already voted!</div>
        <% else %> 
          <a href="javascript:void(0)" class = "alert yesss">yes</a>
          <div class = "hidden"><%= f.id %></div>
          <a href="javascript:void(0)" class = "alert nooo">no</a>
          <div class = "hidden"><%= f.id %></div>
        <% end %>

        <%= link_to "Individual question page", question_path(id: f.id.to_s), method: "get" %>

      </div>
    </div>
    <!-- ################### Main section end ################ -->

  </div>
</div>

  
<% end %>

<!-- ################### Question div end ################ -->

<%= paginate @questions %>