config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :vote_details
  resources :ip_lists
  resources :categories
  resources :categories
  resources :questions
  resources :comments
  devise_for :users
  root 'home#index'

  post 'updateVote' => 'vote_details#create', as: :makevote
  get 'users' => 'home#index'

  namespace :api do
    get 'questions' => 'questions#index'
    get 'questions/:id' => 'questions#show'
    post 'questions' => 'questions#create', as: :api_question_create
    post 'makeComment' => 'comments#create'
    post 'sign_in'  => 'sessions#create', as: :api_sign_in
    delete 'sign_out' => 'sessions#destroy', as: :api_sign_out
    post 'register' => 'users#create', as: :api_user_create
    post 'updateVote' => 'vote_details#create', as: :makevote
  end

end

app/views/layouts/_leftbar.html.erb
<div class="leftbar" data-job-id=<%="#{params[:id]}"%>>

<!--  style="display:block" Removed this from <a> tag comment illegal-->
  <div class = "squares">
    <a href=<%= root_url %> style="color: #000066; font-size: 55px; margin-left: 3px; margin-bottom: 40px; font-family: 'Erica One', cursive; position: relative; bottom: 10px;">V</a>
  </div>

  <%# Category.each do |f|%>
      <%#= link_to f.category, category_path(id: f.id.to_s), method: "get" %>
      <!--<hr>-->
  <%# end %>
  <div class="tooltip" title="Arts">
    <div class = "squares">
      <%= link_to category_path(id: Category.find_by(category: "Arts").id.to_s) do %>
        <i class="fa fa-cubes fa-2x zz" style="text-decoration: none;" id=<%="#{Category.find_by(category: "Arts").id}"%>></i>
      <% end %>
    </div>
  </div>

  <div class="tooltip" title="Sports">
    <div class = "squares">
      <%= link_to category_path(id: Category.find_by(category: "Sports").id.to_s) do %>
        <i class="fa fa-futbol-o fa-2x" style="text-decoration: none; font-size: 2.2em;" id=<%="#{Category.find_by(category: "Sports").id}"%>></i>
      <% end %>
    </div>
  </div>

  <div class="tooltip" title="Knowledge">
    <div class = "squares">
      <%= link_to category_path(id: Category.find_by(category: "Knowledge").id.to_s) do %>
        <i class="fa fa-book fa-2x" style="text-decoration: none; font-size: 2.3em;" id=<%="#{Category.find_by(category: "Knowledge").id}"%>></i>
      <% end %>
    </div>
  </div>

  <div class="tooltip" title="Politics">
    <div class = "squares">
      <%= link_to category_path(id: Category.find_by(category: "Politics").id.to_s) do %>
        <i class="fa fa-globe fa-2x" style="text-decoration: none; font-size: 2.4em;" id=<%="#{Category.find_by(category: "Politics").id}"%>></i>
      <% end %>
    </div>
  </div>

  <div class="tooltip" title="Entertainment">
    <div class = "squares" style = "margin-top: 10px;">
      <%= link_to category_path(id: Category.find_by(category: "Entertainment").id.to_s) do %>
        <i class="fa fa-video-camera fa-2x" style="text-decoration: none; font-size: 2.2em;" id=<%="#{Category.find_by(category: "Entertainment").id}"%>></i>
      <% end %>
    </div>
  </div>

  <div class="tooltip" title="Random">
    <div class = "squares">
      <%= link_to category_path(id: Category.find_by(category: "Random").id.to_s) do %>
        <i class="fa fa-random fa-2x" style="text-decoration: none;" id=<%="#{Category.find_by(category: "Random").id}"%>></i>
      <% end %>
    </div>
  </div>

</div>

<script>
var id;
var $leftbar = $('.leftbar');
$.each($("i"), function(){
  if(this.id == $leftbar.data('job-id')){
    $( this ).css( 'color', '#e5e500' );
    }
  }
);

//if(id = $leftbar.data('job-id'))
    // Do some job things.
</script>

app/views/layouts/_navbar.html.erb
    <div class="contain-to-grid">
      <nav class="top-bar" data-topbar role="navigation">
        <!-- <div class = "row" style="margin: 0; height: 40px; border-bottom-style: solid; border-color: white;">
        </div> -->
        <div class = "row" style="padding-left:50px; padding-top:30px; margin:0;">
          <img src="/images/vyvlogo.png"></img>
        </div>
      </nav>
    </div>

app/views/layouts/_rightbar.html.erb
<!-- ******** good code ******** -->

<div class = "large-3 columns rightbar show-for-large-only">

  <div class = "userinformation">
  
    <% if current_user %>
      <h3><%= current_user.email %></h3>
      <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
      <%= link_to "Make questions", new_question_path, method: "get" %>

    <% else %>

      <h2>Log in</h2>

      <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
        <div class="field">
          <%= f.label :email, :class => 'front_page_label' %><br />
          <%= f.email_field :email, autofocus: true %>
        </div>

        <div class="field">
          <%= f.label :password, :class => 'front_page_label' %><br />
          <%= f.password_field :password, autocomplete: "off" %>
        </div>

        <% if devise_mapping.rememberable? -%>
          <div class="field">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me, :class => 'front_page_label' %>
          </div>
        <% end -%>

        <div class="actions">
        <%= f.submit "Log in" %>
        </div>
      <% end %>

    <%= render "devise/shared/links" %>
  
    <% end %>

  </div>

  <% if current_user %>

  <hr>
    <h4>My Recent Questions</h4>
    <% if current_user %>
      <% (Question.all.where(user_id: current_user.id).count-1).downto (Question.all.where(user_id: current_user.id).count-5) do |a| %>
      <div class = "Questionfeed">
        <% if current_user.questions.first %>
          <% if (a >= 0) %>
            <%= link_to Question.all.where(user_id: current_user.id)[a].text, question_path(id: Question.all.where(user_id: current_user.id)[a].id.to_s), method: "get" %>


            <!--                   Method 1     ---------- -->
            <%# @count = Question.all.where(user_id: current_user.id)[a].vote_details.where(:created_at.gte => current_user.last_sign_in_at).count %>

            <!--                   Method 2     ---------- -->
            <%# @count = Question.all.where(user_id: current_user.id)[a].vote_details.where(seen: false).count %>

            <!--                   Method 3     ---------- -->
            <% @count = Question.all.where(user_id: current_user.id)[a].vote_details.count - Question.all.where(user_id: current_user.id)[a].vote_count_last_seen %>

            <div>New votes: <%= @count %></div>




          <% end %>
        <% end %>

      </div>
      <% end %>
    <% end %>

  <hr>

  <h4>My Recent votes</h4>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vote</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href='https://fonts.googleapis.com/css?family=Erica+One' rel='stylesheet' type='text/css'>

  <!-- ################################# Tooltip ##########################-->
  <script>
        $(document).ready(function() {
            $('.tooltip').tooltipster();
        });
  </script>        
</head>
<body>

    
<div class="row">

  <% if browser.mobile? %>
    <div class="large-12 medium-12 small-12 columns" style = "padding: 0;">
      <div class = "center">
        <%= render 'layouts/navbar' %>        
        <%= yield %>
      </div>
    </div>

  <% else %>
    <div class="large-9 medium-12 small-12 columns" style = "padding: 0;">
      <%= render 'layouts/leftbar' %>
      <div class = "center">
        <%= render 'layouts/navbar' %>
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/rightbar' %>
  <% end %>
</div>


<div class="row">
  <div class="large-10 columns" style="padding-left: 100px;">
  <h5>&copy 2013-<%= Time.now.year %> voteyourview.com </h5>
  </div>
</div>

  


</body>


</html>

<script>
   $(function(){ $(document).foundation({})});


</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-64888518-1', 'auto');
  ga('send', 'pageview');

</script>